name: Trigger Publish-Docs on psmodule.github.io

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/profile/readme.md
      - .github/workflows/Publish-Docs.yml

jobs:
  trigger_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Trigger publish
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          gh auth login
          gh workflow run --repo psmodule/${{ github.repository_owner }}.github.io Publish-Docs.yml
