name: Update profile

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/profile/readme.md
      - .github/workflows/UpdateProfile.yml

jobs:
  update_readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Get GitHub App ID
        id: app
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          gh api "/apps/${{ steps.auth.outputs.app-slug }}[bot]" | ConvertFrom-Json
          $app = gh api "/users/${{ steps.auth.outputs.app-slug }}[bot]" | ConvertFrom-Json
          Write-Verbose ($app | Format-List | Out-String) -Verbose
          "id=$($app.id)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "name=$($app.login)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Update README
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          . ".\scripts\UpdateReadme.ps1"

      - name: Configure Git
        shell: pwsh
        run: |
          git config --global user.name '${{ steps.app.outputs.name }}'
          git config --global user.email '${{ steps.app.outputs.id }}+${{ steps.app.outputs.name }}@users.noreply.github.com>'

      - name: Push changes
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          git add .
          git commit -m "Auto-generated changes"
          git push

  trigger_publish:
    runs-on: ubuntu-latest
    needs: update_readme
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Trigger publish
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          gh workflow run --repo psmodule/${{ github.repository_owner }}.github.io Publish-Docs.yml
