name: Update profile

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  update_readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        uses: PSModule/GitHub-Script@v1
        with:
          ClientID: ${{ secrets.APP_ID }}
          PrivateKey: ${{ secrets.APP_PRIVATE_KEY }}
          Script: |
            LogGroup 'Update README' {
              . ".\scripts\UpdateReadme.ps1"
            }

            $changedFiles = git diff --name-only
            $hasChanges = $null -ne $changedFiles
            "hasChanges=$hasChanges" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

            if (-not $hasChanges) {
              Write-Host 'No change detected'
              return
            }

            Write-Host 'Changes detected:'
            $changedFiles

            LogGroup "Changed files [$($changedFiles.Count)]" {
              $changedFiles | ForEach-Object { Write-Host $_ }
            }

            Get-GitHubContext | Format-List

            git add .
            git commit -m "Auto-generated changes"
            git push

      # - name: Trigger publish
      #   env:
      #     GH_TOKEN: ${{ steps.auth.outputs.token }}
      #   run: |
      #     gh workflow run --repo psmodule/${{ github.repository_owner }}.github.io Publish-Docs.yml
