name: Update profile

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  update_readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update README
        uses: PSModule/GitHub-Script@v1
        with:
          ClientID: ${{ secrets.PSMODULE_CLIENT_ID }}
          PrivateKey: ${{ secrets.PSMODULE_PRIVATE_KEY }}
          Script: scripts/UpdateReadme.ps1
