name: Update profile

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
    shell: pwsh

jobs:
  update_readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README
        uses: PSModule/GitHub-Script@v1
        with:
          ClientID: ${{ secrets.APP_ID }}
          PrivateKey: ${{ secrets.APP_PRIVATE_KEY }}
          Script: |
            LogGroup "Connect to org [$($env:GITHUB_REPOSITORY_OWNER)]" {
              Connect as app to this organization: ${{ github.repository_owner }}
            }
            LogGroup 'Update README' {
              . ".\scripts\UpdateReadme.ps1"
            }

            $changedFiles = git diff --name-only
            $hasChanges = $null -ne $changedFiles
            "hasChanges=$hasChanges" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

            if (-not $hasChanges) {
              Write-Host 'No automated changes detected'
              return
            }

            # git add .
            # Write-Host '::group::Changed files [$($changedFiles.Count)]'
            # $changedFiles | ForEach-Object { Write-Host $_ }
            # Write-Host '::endgroup::'
            # git commit -m "Auto-generated changes"
            # git push

      # - name: Trigger publish
      #   env:
      #     GH_TOKEN: ${{ steps.auth.outputs.token }}
      #   run: |
      #     gh workflow run --repo psmodule/${{ github.repository_owner }}.github.io Publish-Docs.yml
