# Write a github workflow that runs every day at 12:00 UTC and updates the README.md file with the current date and time using PowerShell.
name: Update README

on:
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Get GitHub App ID
        id: app
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]"
