# Write a github workflow that runs every day at 12:00 UTC and updates the README.md file with the current date and time using PowerShell.
name: Update README

on:
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-auth@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Get GitHub App ID
        id: app
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: gh api "/users/${{ steps.auth.outputs.app-slug }}[bot]"
        # run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      # - run: |
      #     git config --global user.name '${{steps.auth.outputs.app-slug}}[bot]'
      #     git config --global user.email '${{steps.get-user-id.outputs.user-id}}+${{ steps.auth.outputs.app-slug }}[bot]@users.noreply.github.com>'

      # - run: |
      #     git add .
      #     git commit -m "Auto-generated changes"
      #     git push
