# Write a github workflow that runs every day at 12:00 UTC and updates the README.md file with the current date and time using PowerShell.
name: Update README

on:
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub App
        id: auth
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.auth.outputs.token }}

      - name: Get GitHub App ID
        id: app
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          $app = gh api "/users/${{ steps.auth.outputs.app-slug }}[bot]" | ConvertFrom-Json
          Write-Verbose ($app | Format-List | Out-String) -Verbose
          "id=$($app.id)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "name=$($app.login)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Configure Git
        shell: pwsh
        run: |
          git config --global user.name '${{steps.app.outputs.name}}'
          git config --global user.email '${{steps.app.outputs.id}}+${{steps.app.outputs.name}}@users.noreply.github.com>'

      - run: |
          git add .
          git commit -m "Auto-generated changes"
          git push
